### PR TITLE
Feature/gyro data

### LINKED ISSUE #4: Reading Gyroscope Data from IMU6050
Since Accelerometer Data is now here now we have to read Gyroscope Data for Angular motion Data which is very crucial to track the movements of gesture. in IMU6050 to read the Gyroscope data we have to follow few steps. 

1. Configure Scaling for Gyroscope Data
2. Read Gyroscope Raw data
3. Calculate is with appropriate Scale we Set

### PR DESCRIPTION
**Pull request by segfaultdev**
The APIs Nedded For Reading Gyroscope Data is Implemented Successfully. Fixes #4

### CODE REVIEW

**Comment by segfaultdev** [comment]
Screenshot from 2024-11-27 12-38-25
here data format `Ax = Accelerometer's X-Axis` and `Gx =  Gyroscope's X-Axis` same for other Data too. Can someone verify those data is there any suspicious value or not.

**Review by zacck — APPROVED** [review]
@undefined2001 I like this and it looks real good, one improvement though from next time try to remember to document your functions especially the inputs and outputs

**Comment by segfaultdev** [comment]
> @undefined2001 I like this and it looks real good, one improvement though from next time try to remember to document your functions especially the inputs and outputs

I will Update the  `README.md` with necessary API's information

**Comment by zacck** [comment]
> > @undefined2001 I like this and it looks real good, one improvement though from next time try to remember to document your functions especially the inputs and outputs
> 
> I will Update the `README.md` with necessary API's information

Hey I meant to add comments to the code describing the functions

**Pull request merged**
